# Generated by Django 4.1.4 on 2025-06-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='custumer_email',
            new_name='customer_email',
        ),
    ]
