# Generated by Django 4.1.4 on 2025-06-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_total_sales_product_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer_adress',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
